# IMPORTAR LIBRERIAS

In [44]:
import matplotlib.pyplot as plt
import cv2
import numpy as np

# USO DE WEBCAM

#### Lectura de la webcam con opencv:
- Insertar el índice de la camara: 0
- o es la camara principal de tu laptop
- cap = cv2.VideoCapture(0)


In [46]:

cap = cv2.VideoCapture(0)
 
# Check if the webcam is opened correctly 
if not cap.isOpened(): 
    raise IOError("Cannot open webcam") 
 
while True: 
    ret, frame = cap.read() 
    frame = cv2.resize(frame,(840,720), interpolation=cv2.INTER_AREA) 
    cv2.imshow('Input', frame) 
 
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break 
 
cap.release() 
cv2.destroyAllWindows() 

# USO DE VIDEO

- En lugar de poner el indice de la camara a usar, se coloca la dirección del video.

In [39]:
cap = cv2.VideoCapture('videos/project_video.mp4')
 
if not cap.isOpened(): 
    raise IOError("Cannot open webcam") 
 
while True: 
    ret, frame = cap.read() 
    frame = cv2.resize(frame,(840,720), interpolation=cv2.INTER_AREA) 
    cv2.imshow('Input', frame) 
 
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break 
 
cap.release() 
cv2.destroyAllWindows() 

# MANEJO CON EL TECLADO
- Se lee el teclado para ver que se ha presionado: cv2.waitKey(1)

In [53]:
print('Maximo entero de 8 bits : ')
print('value         = ',0xFF)
print('binary number = ',bin(0xFF))


Maximo entero de 8 bits : 
value         =  255
binary number =  0b11111111


In [54]:

def print_howto(): 
    print("""
            1. Grayscale - press 'g'
            2. YUV -       press 'y'
            3. HSV -       press 'h'
    """)
if __name__=='__main__': 
    print_howto() 
    cap = cv2.VideoCapture(0) 
 
    # Check if the webcam is opened correctly 
    if not cap.isOpened(): 
        raise IOError("Cannot open webcam") 
 
    cur_mode = None
    while True: 
        # Read the current frame from webcam 
        ret, frame = cap.read() 
        # Resize the captured image 
        frame = cv2.resize(frame, (720,600), interpolation=cv2.INTER_AREA) 
        c = cv2.waitKey(1)
        #print(c) q is c=113
        if c & 0xFF == ord('q'):
            break 
        
        if c != -1 and c != 255 and c != cur_mode:
            cur_mode = c 
 
        if cur_mode == ord('g'): 
            output = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) 
        elif cur_mode == ord('y'): 
            output = cv2.cvtColor(frame, cv2.COLOR_BGR2YUV) 
        elif cur_mode == ord('h'): 
            output = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV) 
        else: 
            output = frame 
        cv2.imshow('Webcam', output) 
 
    cap.release() 
    cv2.destroyAllWindows() 


            1. Grayscale - press 'g'
            2. YUV -       press 'y'
            3. HSV -       press 'h'
    


# MANEJO CON EL MOUSE

### Existen 3 comandos especiales para reconocer eventos con el mouse :

- EVENT_LBUTTONUP
- EVENT_LBUTTONDOWN
- EVENT_MOUSEMOVE

## UP

In [55]:
def print_RGB(event, x, y, flags, params): 
    if event == cv2.EVENT_LBUTTONUP: 
        print(img[x,y,:])
 
if __name__=='__main__': 
    img = cv2.imread('images/pokemon.jpg')
    cv2.namedWindow('Frame') 
    cv2.setMouseCallback('Frame',print_RGB,{"img": img})
 
    while True: 
        img = cv2.resize(img, (720,600), interpolation=cv2.INTER_AREA) 
        cv2.imshow('Frame', img) 
 
        c = cv2.waitKey(1) 
        if c & 0xFF == ord('q'):
            break  
    cv2.destroyAllWindows() 


[48 81 44]
[48 81 44]
[ 61 187 235]
[ 61 187 235]


## DOWN

In [22]:

def print_RGB(event, x, y, flags, params): 
    if event == cv2.EVENT_LBUTTONDOWN: 
        print(img[x,y,:])
if __name__=='__main__': 
    img = cv2.imread('images/pokemon.jpg')
    cv2.namedWindow('Frame') 
    cv2.setMouseCallback('Frame',print_RGB,{"img": img})
 
    while True: 
        img = cv2.resize(img, (720,600), interpolation=cv2.INTER_AREA) 
        cv2.imshow('Frame', img) 
 
        c = cv2.waitKey(1) 
        if c & 0xFF == ord('q'):
            break  
    cv2.destroyAllWindows() 


[ 53  76 135]
[ 61 187 235]
[ 61 187 235]
[ 61 187 235]
[ 61 187 235]


## MOVE

- Imprimir los valores RGB de cada pixel, cuando el mouse se encuentre apuntando a este


In [56]:
# font 
font = cv2.FONT_HERSHEY_SIMPLEX 
# coordenate
org = (50, 50) 
# fontScale 
fontScale = 1
# Blue color in BGR 
color = (255, 0, 0)   
# Line thickness of 2 px 
thickness = 2
# Using cv2.putText() method 

def print_RGB(event, x, y, flags, params): 
    global img_aux,img
    img = img_aux.copy()
    if event == cv2.EVENT_MOUSEMOVE: 
        img = cv2.putText(img,str(img_aux[y,x,:]), org, font,  
                   fontScale, color, thickness, cv2.LINE_AA) 

 
if __name__=='__main__': 
    img = cv2.imread('images/pokemon.jpg')
    img = cv2.resize(img, (720,600), interpolation=cv2.INTER_AREA) 
    img_aux = img.copy()
    cv2.namedWindow('Frame') 
    cv2.setMouseCallback('Frame',print_RGB,{"img": img})
    while True: 
        cv2.imshow('Frame', img) 
        c = cv2.waitKey(1) 
        if c & 0xFF == ord('q'):
            break  
    cv2.destroyAllWindows() 


# Aplicaciones

### Detección de cuadrante dentro de una imagen
- Haciendo click con el mouse se obtiene el cuadrante y se modifica el color de todos los pixeles que pertenecen a este

In [62]:

def detect_quadrant(event, x, y, flags, param): 
    if event == cv2.EVENT_LBUTTONDOWN: 
        if x > width/2: 
            if y > height/2: 
                point_top_left = (int(width/2), int(height/2)) 
                point_bottom_right = (width-1, height-1) 
            else: 
                point_top_left = (int(width/2), 0) 
                point_bottom_right = (width-1, int(height/2)) 
 
        else: 
            if y > height/2: 
                point_top_left = (0, int(height/2)) 
                point_bottom_right = (int(width/2), height-1) 
            else: 
                point_top_left = (0, 0) 
                point_bottom_right = (int(width/2), int(height/2)) 

        img = param["img"]
        # Repaint all in white again
        cv2.rectangle(img, (0,0), (width-1,height-1), (255,255,255), -1)
        # Paint green quadrant 
        cv2.rectangle(img, point_top_left, point_bottom_right, (0,100,0), -1) 
 
if __name__=='__main__': 
    width, height = 640, 480 
    img = 255 * np.ones((height, width, 3), dtype=np.uint8) 
    cv2.namedWindow('Input window') 
    cv2.setMouseCallback('Input window', detect_quadrant, {"img": img}) 
 
    while True: 
        cv2.imshow('Input window', img) 
        c = cv2.waitKey(1) 
        if c & 0xFF == ord('q'):
            break 
 
    cv2.destroyAllWindows()

### Dibujar un cuadrado

- Se dibujara un cuadrado seleccionando 2 puntos de la imagen 

In [ ]:

def draw_rectangle(event, x, y, flags, params): 
    global x_init, y_init, drawing
    def update_pts():
        params["top_left_pt"] = (min(x_init, x), min(y_init, y))
        params["bottom_right_pt"] = (max(x_init, x), max(y_init, y))
        #img[y_init:y, x_init:x] = 255 - img[y_init:y, x_init:x]
    if event == cv2.EVENT_LBUTTONDOWN: 
        drawing = True 
        x_init, y_init = x, y 
 
    elif event == cv2.EVENT_MOUSEMOVE and drawing:
        update_pts() 
 
    elif event == cv2.EVENT_LBUTTONUP: 
        drawing = False 
        update_pts() 
 
if __name__=='__main__': 
    drawing = False 
    event_params = {"top_left_pt": (-1, -1), "bottom_right_pt": (-1, -1)}

    cv2.namedWindow('Frame') 
    cv2.setMouseCallback('Frame', draw_rectangle, event_params) 
    frame = cv2.imread('images/pokemon.jpg')
    while True: 
        
        img = cv2.resize(frame, (840,720), interpolation=cv2.INTER_AREA) 
        (x0,y0), (x1,y1) = event_params["top_left_pt"], event_params["bottom_right_pt"]
        #img[y0:y1, x0:x1] = 255 - img[y0:y1, x0:x1] 
        img = cv2.rectangle(img,(x0,y0),(x1,y1),(0,255,0),3)
        cv2.imshow('Frame', img) 
 
        c = cv2.waitKey(1) 
        if c & 0xFF == ord('q'):
            break  
    cv2.destroyAllWindows() 


### MODIFICAR UNA IMAGEN SELECCIONANDO SU CUADRANTE

In [65]:

def detect_quadrant(event, x, y, flags, param): 
    global img_aux
    if event == cv2.EVENT_LBUTTONDOWN: 
        if x > width/2: 
            if y > height/2: 
                point_top_left = (int(width/2), int(height/2)) 
                point_bottom_right = (width-1, height-1) 
            else: 
                point_top_left = (int(width/2), 0) 
                point_bottom_right = (width-1, int(height/2)) 
 
        else: 
            if y > height/2: 
                point_top_left = (0, int(height/2)) 
                point_bottom_right = (int(width/2), height-1) 
            else: 
                point_top_left = (0, 0) 
                point_bottom_right = (int(width/2), int(height/2)) 

        img = param["img"]
        # Repaint all in white again
        #cv2.rectangle(img, (0,0), (width-1,height-1), (255,255,255), -1)
        # Paint green quadrant 
        img_aux = img.copy()
        cv2.rectangle(img_aux, point_top_left, point_bottom_right, (0,100,0), -1) 
 
if __name__=='__main__': 
    width, height = 640, 480 
    #img = 255 * np.ones((height, width, 3), dtype=np.uint8) 
    img = cv2.imread('images/pokemon.jpg')
    img = cv2.resize(img,(width,height))
    img_aux = img.copy()
    cv2.namedWindow('Input window') 
    cv2.setMouseCallback('Input window', detect_quadrant, {"img": img}) 
 
    while True: 
        cv2.imshow('Input window', img_aux) 
        c = cv2.waitKey(1) 
        if c & 0xFF == ord('q'):
            break 
 
    cv2.destroyAllWindows()

### Dibujar un cuadrante usando la webcam

In [68]:

def draw_rectangle(event, x, y, flags, params): 
    global x_init, y_init, drawing
    def update_pts():
        params["top_left_pt"] = (min(x_init, x), min(y_init, y))
        params["bottom_right_pt"] = (max(x_init, x), max(y_init, y))
        #img[y_init:y, x_init:x] = 255 - img[y_init:y, x_init:x]
    if event == cv2.EVENT_LBUTTONDOWN: 
        drawing = True 
        x_init, y_init = x, y 
 
    elif event == cv2.EVENT_MOUSEMOVE and drawing:
        update_pts() 
 
    elif event == cv2.EVENT_LBUTTONUP: 
        drawing = False 
        update_pts() 
 
if __name__=='__main__': 
    drawing = False 
    event_params = {"top_left_pt": (-1, -1), "bottom_right_pt": (-1, -1)}
 
    cap = cv2.VideoCapture(0) 
 
    # Check if the webcam is opened correctly 
    if not cap.isOpened(): 
        raise IOError("Cannot open webcam") 
 
    cv2.namedWindow('Webcam') 
    cv2.setMouseCallback('Webcam', draw_rectangle, event_params) 
 
    while True: 
        ret, frame = cap.read() 
        img = cv2.resize(frame, (840,720), interpolation=cv2.INTER_AREA) 
        (x0,y0), (x1,y1) = event_params["top_left_pt"], event_params["bottom_right_pt"]
        #img[y0:y1, x0:x1] = 255 - img[y0:y1, x0:x1] 
        img = cv2.rectangle(img,(x0,y0),(x1,y1),(0,255,0),3)
        cv2.imshow('Webcam', img) 
 
        c = cv2.waitKey(1) 
        if c & 0xFF == ord('q'):
            break  
 
    cap.release() 
    cv2.destroyAllWindows() 
